//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUser
    {
        public int U_Id { get; set; }
        public string U_Name { get; set; }
        public string U_Email { get; set; }
        public string U_Password { get; set; }
        public string U_Address { get; set; }
        public string U_Phone { get; set; }
        public Nullable<bool> U_Isvalid { get; set; }
        public string U_Fname { get; set; }
    }
}
